# Generated by Django 3.2.18 on 2023-05-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20230426_0011'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('proveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=4)),
                ('precio', models.IntegerField(max_length=30)),
                ('SubTotalDetalle', models.FloatField(default=0)),
                ('DescuentoDetalle', models.FloatField(default=0)),
                ('TotalDetalle', models.FloatField(default=0)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
