# Generated by Django 3.2.18 on 2023-05-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_compras_detalle_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='DescuentoDetalle',
            new_name='descuento_detalle',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='SubTotalDetalle',
            new_name='sub_total_detalle',
        ),
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='TotalDetalle',
            new_name='total_detalle',
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
