# Generated by Django 3.2.18 on 2023-05-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20230504_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_orden',
            old_name='compras',
            new_name='compra',
        ),
    ]
